### PR TITLE
social-auth-google

### PR DESCRIPTION
**Pull request by Adtrex**

### CODE REVIEW

**Comment by onifs10** [comment]
pls pull from the hng repo again to have the updated code base ... and work with the User table we are using ..
 send a screenshot of tested login ...

**Comment by onifs10** [comment]
still check your code ... the User table we are using slits the name column in first name and lastname 
Screenshot from 2020-06-30 22-04-43

**Comment by Adtrex** [comment]
image

**Comment by Adtrex** [comment]
I don't understand what you meant by "the User table we are using slits the name column in first name and lastname"

**Comment by onifs10** [comment]
if you have the latest pull go through the SocialController i made

**Pull request merged**
