### PR TITLE
Unfunded Campaigns

### PR DESCRIPTION
**Pull request by nkemjikaobi**
**FIXES 194....It skipped my mind **

To view users that have not received funding, go to the route **'unfunded-campaigns'**
This is a protected route so only authenticated users are allowed access.

The image below shows a table of the users who haven't received funding from oldest to the most recent
Screenshot 2020-07-10 16 39 18

The image below shows the pagination
Screenshot 2020-07-10 16 39 36

### CODE REVIEW

**Comment by nkemjikaobi** [comment]
FIXES 194...It skipped my mind 🙏🏽🙏🏽

**Comment by onifs10** [comment]
don't touch the Api folder ..

**Comment by nkemjikaobi** [comment]
Nothing was touched

**Comment by nkemjikaobi** [comment]
That’s where the request controller is

**Comment by gblend** [comment]
The RequestController you used was in Controller/Api/ folder instead of the one in Controller

**Comment by nkemjikaobi** [comment]
Ooh my bad...Let me change it

**Pull request closed without merging**
