### PR TITLE
Fixed #182

### LINKED ISSUE #182: Redirct to 404
"Implement our customized 404 page and make sure pages that does
not exist brings out the 404 page"

### PR DESCRIPTION
**Pull request by ajadi473**

### CODE REVIEW

**Comment by onifs10** [comment]
what are you working on

**Comment by ajadi473** [comment]
"Implement our customized 404 page and make sure pages that does
not exist brings out the 404 page"

**Comment by ajadi473** [comment]
The broken links were additional bugs I noticed and fixed

**Comment by ajadi473** [comment]
Yes most definitely.

**Pull request merged**
