### PR TITLE
Fixes #17

### LINKED ISSUE #17: View all Funders Favorite Request endpoint
* Fetch all request marked as favorite by funder.

### PR DESCRIPTION
**Pull request by sodiadrhain**
**Added / Updated
-Api route to fetch all request marked as favourite... from "routes/api.php".
-Created a function in "Controllers/Api/FavrouriteController.php" to fetch details and send json response.
-Modified Model "Favorites" to link a favorite to a request in other to have the requestID details in the response.

**Screenshots
Screenshot (316)
Screenshot (318)
Screenshot (319)
Screenshot (320)

**Testing
-http://localhost:8000/api/v1/marked-requests-favorite/{userId}
-http://127.0.0.1:8000/api/v1/marked-requests-favorite/{userId}
-http://fundmylaptop.herokuapp.com/api/v1/marked-requests-favorite/{userId}

### CODE REVIEW

**Comment by kelrob** [comment]
Perfect Job bro, but can you auth the user before returning the response, cos right now anyone can access this endpoint without being logged in which is not what we want.

One more thing kindly pull the update from the repo before making a new PR. Other than that. Job well done bro.

**Comment by sodiadrhain** [comment]
Hmm, okay Boss... 

But i thought the Api, is under a middleware auth, which means only auth persons can access the Api

**Comment by sodiadrhain** [comment]
Or, do you mean...

Auth that particular user with the ID of favorite request being fetched?

**Comment by sodiadrhain** [comment]
Because for example i thought who ever will be fetching a marked favorite won't be the actual user... do you understand my view Boss?

**Comment by sodiadrhain** [comment]
I check if user is authenticated i.e if auth::, in my next commit...

**Pull request closed without merging**
